name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install stable Rust
        run: rustup toolchain install stable --profile minimal
      - name: Test
        run: cargo test --workspace --locked
        working-directory: surface
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
        working-directory: surface
      - name: Check launcher is absent
        run: surface/scripts/check-launcher-absent.sh
